export default [
    {
        id: 1,
        postedOn: '2025-01-11',
        title: 'Frontend Developer',
        company: 'Amazon',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['JavaScript', 'Node.js', 'React.js'],
        job_link: 'https://www.amazon.jobs/en/'
    },
    {
        id: 2,
        postedOn: '2025-01-07',
        title: 'Data Scientist',
        company: 'Google',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'Hybrid',
        skills: ['Python', 'Machine Learning', 'Data Analysis'],
        job_link: 'https://careers.google.com/'
    },
    {
        id: 3,
        postedOn: '2025-01-02',
        title: 'Backend Developer',
        company: 'Microsoft',
        type: 'Full Time',
        experience: 'Junior Level',
        location: 'In-Office',
        skills: ['Node.js', 'Express', 'MongoDB'],
        job_link: 'https://careers.microsoft.com/'
    },
    {
        id: 4,
        postedOn: '2024-11-01',
        title: 'AI Engineer',
        company: 'OpenAI',
        type: 'Contract',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['Python', 'TensorFlow', 'Natural Language Processing'],
        job_link: 'https://openai.com/careers'
    },
    {
        id: 5,
        postedOn: '2024-11-05',
        title: 'UI/UX Designer',
        company: 'Adobe',
        type: 'Part Time',
        experience: 'Junior Level',
        location: 'Remote',
        skills: ['Figma', 'Adobe XD', 'Sketch'],
        job_link: 'https://adobe.wd5.myworkdayjobs.com/en-US/external_experience'
    },
    {
        id: 6,
        postedOn: '2024-11-08',
        title: 'DevOps Engineer',
        company: 'IBM',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'On-Site',
        skills: ['Docker', 'Kubernetes', 'CI/CD'],
        job_link: 'https://careers.ibm.com/'
    },
    {
        id: 7,
        postedOn: '2024-11-10',
        title: 'Machine Learning Engineer',
        company: 'Meta',
        type: 'Internship',
        experience: 'Intern',
        location: 'Hybrid',
        skills: ['Python', 'Deep Learning', 'PyTorch'],
        job_link: 'https://www.metacareers.com/'
    },
    {
        id: 8,
        postedOn: '2024-11-15',
        title: 'Full Stack Developer',
        company: 'Netflix',
        type: 'Freelance',
        experience: 'Team Lead',
        location: 'Work from Anywhere',
        skills: ['React.js', 'Node.js', 'PostgreSQL'],
        job_link: 'https://jobs.netflix.com/'
    },
    {
        id: 9,
        postedOn: '2024-11-18',
        title: 'Cloud Engineer',
        company: 'AWS',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['AWS', 'Terraform', 'CloudFormation'],
        job_link: 'https://aws.amazon.com/careers/'
    },
    {
        id: 10,
        postedOn: '2024-11-20',
        title: 'Product Manager',
        company: 'Tesla',
        type: 'Full Time',
        experience: 'Managerial',
        location: 'Hybrid',
        skills: ['Agile', 'Scrum', 'Leadership'],
        job_link: 'https://www.tesla.com/careers'
    },
    {
        id: 11,
        postedOn: '2024-11-22',
        title: 'Cybersecurity Specialist',
        company: 'Cisco',
        type: 'Part Time',
        experience: 'Senior Level',
        location: 'On-Site',
        skills: ['Penetration Testing', 'Network Security', 'Ethical Hacking'],
        job_link: 'https://jobs.cisco.com/'
    },
    {
        id: 12,
        postedOn: '2024-11-25',
        title: 'Blockchain Developer',
        company: 'Binance',
        type: 'Contract',
        experience: 'Junior Level',
        location: 'Remote',
        skills: ['Solidity', 'Ethereum', 'Blockchain'],
        job_link: 'https://www.binance.com/en/careers'
    },
    {
        id: 13,
        postedOn: '2024-11-28',
        title: 'AR/VR Developer',
        company: 'Unity',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Flexible Location',
        skills: ['Unity', 'C#', 'ARKit'],
        job_link: 'https://careers.unity.com/'
    },
    {
        id: 14,
        postedOn: '2024-12-01',
        title: 'QA Engineer',
        company: 'Dell',
        type: 'Full Time',
        experience: 'Junior Level',
        location: 'In-Office',
        skills: ['Selenium', 'JUnit', 'Testing Automation'],
        job_link: 'https://jobs.dell.com/'
    },
    {
        id: 15,
        postedOn: '2024-12-03',
        title: 'Embedded Systems Engineer',
        company: 'Intel',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Hybrid',
        skills: ['C', 'RTOS', 'IoT'],
        job_link: 'https://jobs.intel.com/'
    },
    {
        id: 16,
        postedOn: '2024-12-05',
        title: 'Site Reliability Engineer',
        company: 'LinkedIn',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'Hybrid',
        skills: ['Linux', 'Kubernetes', 'Monitoring Tools'],
        job_link: 'https://careers.linkedin.com/'
    },
    {
        id: 17,
        postedOn: '2024-12-08',
        title: 'Mobile App Developer',
        company: 'Spotify',
        type: 'Contract',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['React Native', 'Swift', 'Kotlin'],
        job_link: 'https://www.spotifyjobs.com/'
    },
    {
        id: 18,
        postedOn: '2024-12-10',
        title: 'Game Developer',
        company: 'Epic Games',
        type: 'Full Time',
        experience: 'Junior Level',
        location: 'Flexible Location',
        skills: ['Unreal Engine', 'C++', 'Game Design'],
        job_link: 'https://www.epicgames.com/careers'
    },
    {
        id: 19,
        postedOn: '2024-12-12',
        title: 'Software Engineer',
        company: 'Oracle',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'On-Site',
        skills: ['Java', 'Spring Boot', 'SQL'],
        job_link: 'https://www.oracle.com/corporate/careers/'
    },
    {
        id: 20,
        postedOn: '2024-12-14',
        title: 'Android Developer',
        company: 'Samsung',
        type: 'Part Time',
        experience: 'Junior Level',
        location: 'Remote',
        skills: ['Kotlin', 'Android Studio', 'APIs'],
        job_link: 'https://www.samsung.com/us/careers/'
    },
    {
        id: 21,
        postedOn: '2024-12-16',
        title: 'Developer Advocate',
        company: 'Twilio',
        type: 'Full Time',
        experience: 'Team Lead',
        location: 'Remote',
        skills: ['Public Speaking', 'API Documentation', 'Developer Relations'],
        job_link: 'https://www.twilio.com/company/jobs'
    },
    {
        id: 22,
        postedOn: '2024-12-18',
        title: 'Cloud Engineer',
        company: 'Google Cloud',
        type: 'Internship',
        experience: 'Intern',
        location: 'Hybrid',
        skills: ['Google Cloud Platform', 'DevOps', 'Terraform'],
        job_link: 'https://cloud.google.com/careers'
    },
    {
        id: 23,
        postedOn: '2024-12-20',
        title: 'QA Engineer',
        company: 'Slack',
        type: 'Freelance',
        experience: 'Senior Level',
        location: 'Remote',
        skills: ['Test Cases', 'Automation', 'Agile Testing'],
        job_link: 'https://slack.com/careers'
    },
    {
        id: 24,
        postedOn: '2024-12-22',
        title: 'Blockchain Developer',
        company: 'Coinbase',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'On-Site',
        skills: ['Blockchain Architecture', 'Ethereum', 'Solidity'],
        job_link: 'https://www.coinbase.com/careers'
    },
    {
        id: 25,
        postedOn: '2024-12-24',
        title: 'AI Engineer',
        company: 'DeepMind',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'In-Office',
        skills: ['AI Research', 'Python', 'Reinforcement Learning'],
        job_link: 'https://www.deepmind.com/careers'
    }
];